### ISSUE TITLE
Screenshot Colorscheme

### ISSUE THREAD

**Issue by mikelerch** [girishji/bufline.vim#2]
Hey,

Great work on the plugin. I was wondering if you still happen to have the name of the colorscheme, or if it's a custom one, if you would mind sharing?

Thanks in advance!

**Comment by girishji** [comment]
I moved away from using Vim themes. I just set the 16 colors shown in iTerm. In Vim I use 'cterm' colors, not 'gui' colors. Very basic. I don't remember that theme from screenshot but you can easily reproduce it:
- Font is "CMU Typewriter Text"
- To get that dark line `set fillchars+=stl:―,stlnc:—`
- bg is `f6e9e7` and fg color is black. you adjust other colors by eyeballing.

You could look at some syntax adjustments I made: https://github.com/girishji/declutter.vim

Sometime ago I did experiment with fancy color themes. I don't use it anymore but you can take inspiration:
https://github.com/girishji/declutter.nvim
